version: "2"
services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: proxy
    restart: always
    networks:
      - skynet

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    networks:
      - skynet
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=portainer.ptflp.ru
      - VIRTUAL_PORT=9000

  cloud:
    build: ./spring_cloud
    container_name: microservice_cloud
    restart: always
    networks:
      - skynet
    environment:
      - VIRTUAL_HOST=java.ptflp.ru
      - VIRTUAL_PORT=8080

  flask:
    build: ./flask
    container_name: test_flask
    restart: always
    networks:
      - skynet
    environment:
      - VIRTUAL_HOST=python.ptflp.ru
      - VIRTUAL_PORT=5000

networks:
  skynet:
    external:
      name: skynet